### ISSUE TITLE
## Issue: Dependency Conflict with `env_logger`  ### Description  When trying to install the `dify-openai-apis` package, I encountered a dependency conflict with the `env_logger` crate. The error message is as follows:

### ISSUE THREAD

**Issue by Mgrsc** [rming/dify-openai-apis#1]
### Description

When trying to install the `dify-openai-apis` package, I encountered a dependency conflict with the `env_logger` crate. The error message is as follows:
![image](https://github.com/rming/dify-openai-apis/assets/118801216/262cf311-2987-4c16-8cda-c52cad3d1499)

**Comment by 12kv** [comment]
Please use `rustup update` to upgrade Rust to the latest version, and then try compiling again.   
I'll include the minimum Rust version requirement in the next release.

**Comment by Mgrsc** [comment]
> Please use `rustup update` to upgrade Rust to the latest version, and then try compiling again. I'll include the minimum Rust version requirement in the next release.
Thanks , compilation successful.
