### ISSUE TITLE
Error occurred when using this API in some applications.

### ISSUE THREAD

**Issue by Mgrsc** [rming/dify-openai-apis#2]
I found that when I call this API interface on front-end pages like chatgpt-next-web, it works fine. But when I call the same interface in some applications, such as Qchatgpt and chatgpt on WeChat, it gives an error instead of returning the expected output. I'd like to know if the program hasn't fully implemented OpenAI's request format or if there's an issue with my configuration.
![image](https://github.com/rming/dify-openai-apis/assets/118801216/2262a77a-8e87-4b0f-98a0-5c59a7ff2ce3)

**Comment by 12kv** [comment]
We have only implemented the `/v1/chat/completions` API for now. 
I'll try the UI you mentioned later.

https://github.com/rming/dify-openai-apis/blob/ab96a2abee758a967f49019d3eba232f3c6942a8/src/server/mod.rs#L29-L32
